Output demo.gif
Set FontSize 14
Set Width 1920
Set Height 1080
Set Theme "Catppuccin Mocha"
Set Padding 20
Set Framerate 24

Type "lfk"
Enter
Sleep 5s
Type "/"
Sleep 1s
Type "pod"
Sleep 1s
Enter
Type "l"
Sleep 3s
Type "j"
Sleep 2s
Type "j"
Sleep 2s
Type "j"
Sleep 2s
Type "h"
Sleep 1s
Type "j"
Sleep 1s
Type "l"
Sleep 1s
Type "j"
Sleep 1s
Type "j"
Sleep 1s
Type "j"
Sleep 1s
Type "j"
Sleep 1s
Ctrl+L
Sleep 5s
Type "q"
Sleep 1s
Enter
Type "jj"
Sleep 1s
Type "z"
Sleep 1s
Type "/containers"
Enter
Sleep 3s
Type "qq"
Sleep 1s
Type "h"
Type "/"
Sleep 1s
Type "service"
Sleep 3s
Enter
Type "l"
Type "x"
Sleep 4s
Type "p"
Sleep 500ms
Enter
Sleep 2s
Ctrl+c
