Output themes.gif
Set FontSize 16
Set Width 1920
Set Height 1080
Set Theme "Catppuccin Mocha"
Set Padding 20

Type "lfk"
Enter
Sleep 1s
Type "T"
Sleep 2s
Type "t"
Sleep 2s
Type "t"
Sleep 1s
Type "k"
Sleep 1s
Type "k"
Sleep 1s
Type "/catpp"
Enter
Sleep 2s
Type "/kanagawa-wave"
Enter
Sleep 2s
Type "/nord"
Enter
Sleep 2s
Type "/synthwave-everything"
Enter
Sleep 2s
Type "/bluloco"
Enter
Sleep 2s
Ctrl+c
