Output themes.gif
Set FontSize 16
Set Width 1920
Set Height 1080
Set Theme "Catppuccin Mocha"
Set Padding 20
Set Framerate 24

Type "lfk"
Enter
Sleep 1s
Type "T"
Sleep 2s
Type "k"
Sleep 1s
Type "k"
Sleep 3s
Type "k"
Sleep 3s
Type "k"
Sleep 3s
Type "/catpp"
Enter
Sleep 3s
Type "/kanagawa-wave"
Sleep 3s
Escape
Type "/nord"
Enter
Sleep 3s
Type "/synthwave-everything"
Sleep 3s
Escape
Type "/bluloco"
Enter
Sleep 3s
Ctrl+c
