Output themes.gif
Set FontSize 16
Set Width 1920
Set Height 1080
Set Theme "Catppuccin Mocha"
Set Padding 20
Set Framerate 24

Type "lfk"
Enter
Sleep 1
Type "T"
Sleep 2
Type "k"
Sleep 1
Type "k"
Sleep 3
Type "k"
Sleep 3
Type "k"
Sleep 3
Type "/catpp"
Enter
Sleep 3
Type "/kanagawa-wave"
Sleep 3
Escape
Type "/nord"
Enter
Sleep 3
Type "/synthwave-everything"
Sleep 3
Escape
Type "/bluloco"
Enter
Sleep 3
Ctrl+c
