FROM alpine:3.24@sha256:a2d49ea686c2adfe3c992e47dc3b5e7fa6e6b5055609400dc2acaeb241c829f4

RUN apk add --no-cache \
    ca-certificates \
    helm \
    kubectl \
    && addgroup -S lfk \
    && adduser -S lfk -G lfk

COPY lfk /usr/local/bin/lfk

ENV TERM=xterm-256color
ENV COLORTERM=truecolor

USER lfk

ENTRYPOINT ["lfk"]
