FROM alpine:3.23@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

RUN apk add --no-cache \
    ca-certificates \
    helm \
    kubectl \
    && addgroup -S lfk \
    && adduser -S lfk -G lfk

COPY lfk /usr/local/bin/lfk

ENV TERM=xterm-256color
ENV COLORTERM=truecolor

USER lfk

ENTRYPOINT ["lfk"]
