FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

RUN apk add --no-cache \
    ca-certificates \
    helm \
    kubectl \
    && addgroup -S lfk \
    && adduser -S lfk -G lfk

COPY lfk /usr/local/bin/lfk

ENV TERM=xterm-256color
ENV COLORTERM=truecolor

USER lfk

ENTRYPOINT ["lfk"]
